const header = document.querySelector('[data-header]');
const menuToggle = document.querySelector('.menu-toggle');
const navPanel = document.querySelector('.nav-panel');
const closeMenu = () => { navPanel.classList.remove('open'); menuToggle.setAttribute('aria-expanded', 'false'); menuToggle.setAttribute('aria-label', 'Open menu'); };
menuToggle.addEventListener('click', () => { const isOpen = navPanel.classList.toggle('open'); menuToggle.setAttribute('aria-expanded', String(isOpen)); menuToggle.setAttribute('aria-label', isOpen ? 'Close menu' : 'Open menu'); });
document.querySelectorAll('a[href^="#"]').forEach((link) => link.addEventListener('click', closeMenu));
window.addEventListener('scroll', () => header.classList.toggle('scrolled', window.scrollY > 20), { passive: true });
const revealObserver = new IntersectionObserver((entries, observer) => { entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } }); }, { threshold: 0.12 });
document.querySelectorAll('.reveal').forEach((element) => revealObserver.observe(element));
const form = document.querySelector('#contactForm');
const status = document.querySelector('.form-status');
form.addEventListener('submit', (event) => { event.preventDefault(); status.textContent = 'Thanks. We will be in touch soon.'; form.reset(); });
